# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

use_frameworks!
target 'SaveNSpend' do
pod 'RealmSwift'
end

target 'SaveNSpendTests' do
pod 'RealmSwift'
end

